name: release

on:
  release:
    types: [published]

# Required for updating published release contents
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Root directory for doing Ghidra work (building, etc.)
        root: ["/tmp/ghidra"]
        # Repository name ("Cartographer")
        name: ["${{github.event.repository.name}}"]
        # Ghidra build version(s)
        version: [10.3]
        include:
          - version: 10.3
            release_url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3_build
            filename: ghidra_10.3_PUBLIC_20230510.zip
            directory: ghidra_10.3_PUBLIC

    steps:
      - uses: actions/checkout@v3

      - name: Download Ghidra
        run: |
          wget -P ${{matrix.root}} -q ${{matrix.release_url}}/${{matrix.filename}}
          unzip -d ${{matrix.root}} -q ${{matrix.root}}/${{matrix.filename}}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build plugin via gradle
        run: gradle -PGHIDRA_INSTALL_DIR=${{matrix.root}}/${{matrix.directory}}

      - name: Rename ZIP for upload
        run: mv dist/*_${{matrix.version}}_*.zip dist/ghidra_${{matrix.version}}_${{matrix.name}}.zip

      - name: Upload release ZIP
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload ${{github.event.release.tag_name}} dist/ghidra_${{matrix.version}}_${{matrix.name}}.zip
